import { JobPosting } from "../dtos/job.dto";
import { getCompanyLogoUrl } from "../utils/logo-resolver";

export const INITIAL_JOBS_DATA: JobPosting[] = [
  {
    id: "job-ba-hcm-01",
    title: "Senior Business Analyst (Fintech & Core Payment)",
    company: "VNPay Solutions Vietnam",
    companyLogo: getCompanyLogoUrl("VNPay"),
    location: "HO_CHI_MINH",
    locationDetails: "Quận 1, TP. Hồ Chí Minh",
    roleCategory: "BUSINESS_ANALYST",
    seniority: "SENIOR",
    salaryRange: {
      min: 42000000,
      max: 58000000,
      currency: "VND",
      display: "42 - 58 Triệu VNĐ (~$1.700 - $2.300)",
    },
    workMode: "HYBRID",
    experienceYearsRequired: 4,
    postedDate: "2026-08-15",
    isHot: true,
    linkedinUrl: "https://www.linkedin.com/jobs/view/senior-business-analyst-vnpay-hcm",
    responsibilitiesSummary: [
      "Khơi gợi, thu thập và làm rõ yêu cầu nghiệp vụ cổng thanh toán liên ngân hàng và ví điện tử.",
      "Soạn thảo tài liệu đặc tả yêu cầu BRD, SRS, User Story và tiêu chí nghiệm thu Acceptance Criteria chuẩn BABOK.",
      "Thiết kế mô hình quy trình BPMN 2.0 và tài liệu hóa luồng tương tác API với các tổ chức tài chính.",
      "Chủ trì phối hợp cùng các đội ngũ Agile và giám sát triển khai kiểm thử chấp nhận UAT.",
    ],
    requirementsSummary: [
      "Tối thiểu 4 năm kinh nghiệm làm Senior Business Analyst trong ngành Fintech, Ngân hàng hoặc E-commerce.",
      "Nắm vững chuẩn BABOK v3, kỹ năng đặc tả yêu cầu và vẽ sơ đồ BPMN, UML (Activity, Sequence).",
      "Thành thạo truy vấn SQL nâng cao phục vụ phân tích dữ liệu giao dịch và đối soát.",
      "Kỹ năng đàm phán, quản lý các bên liên quan và tiếng Anh giao tiếp chuyên nghiệp.",
    ],
    extractedSkills: [
      { name: "Requirements Engineering", category: "CORE", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "Process Modeling (BPMN/UML)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "User Story & Acceptance Criteria", category: "CORE", importance: "MUST_HAVE" },
      { name: "SQL (Advanced Querying)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "API Analysis & Postman", category: "TOOL", importance: "MUST_HAVE" },
      { name: "Fintech & Banking", category: "DOMAIN", importance: "MUST_HAVE" },
      { name: "Stakeholder Management", category: "SOFT_SKILL", importance: "MUST_HAVE" },
    ],
    jobDescription: `Tuyển dụng Senior Business Analyst dẫn dắt dự án nâng cấp hệ thống thanh toán liên ngân hàng tại TP.HCM. Mức thu nhập hấp dẫn từ 42 đến 58 triệu VNĐ.`,
  },
  {
    id: "job-da-hcm-02",
    title: "Lead Data Analyst (E-Commerce Growth & Big Data)",
    company: "Shopee Vietnam Growth Lab",
    companyLogo: getCompanyLogoUrl("Shopee"),
    location: "HO_CHI_MINH",
    locationDetails: "Quận 7, TP. Hồ Chí Minh",
    roleCategory: "DATA_ANALYST",
    seniority: "LEAD_MANAGER",
    salaryRange: {
      min: 50000000,
      max: 75000000,
      currency: "VND",
      display: "50 - 75 Triệu VNĐ (~$2.000 - $3.000)",
    },
    workMode: "ON_SITE",
    experienceYearsRequired: 5,
    postedDate: "2026-08-16",
    isHot: true,
    linkedinUrl: "https://www.linkedin.com/jobs/view/lead-data-analyst-shopee-hcm",
    responsibilitiesSummary: [
      "Xây dựng cây chỉ số KPI đo lường toàn diện tăng trưởng người dùng, tỷ lệ chuyển đổi và giá trị trọn đời (LTV).",
      "Thiết kế và tối ưu các mô hình dữ liệu DWH trên nền tảng BigQuery / Redshift / Snowflake.",
      "Phát triển hệ thống Dashboard Power BI và Tableau theo dõi thời gian thực cho ban giám đốc khối.",
      "Chủ trì thiết kế thử nghiệm A/B Testing và phân tích thống kê định lượng đưa ra đề xuất tối ưu doanh thu.",
    ],
    requirementsSummary: [
      "Từ 5 năm kinh nghiệm chuyên sâu về Data Analytics, ưu tiên ngành E-Commerce hoặc Tech Unicorn.",
      "Thành thạo SQL nâng cao (Window Functions, CTEs, Indexing), Python (Pandas, NumPy, Scikit-learn).",
      "Kinh nghiệm sâu rộng về Power BI, viết DAX phức tạp, Tableau, Star Schema.",
      "Tư duy thống kê vững chắc (Statistical Analysis, Hypothesis Testing) và kỹ năng trình bày xuất sắc.",
    ],
    extractedSkills: [
      { name: "SQL (Advanced Querying)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 5 },
      { name: "Python for Data Analytics", category: "CORE", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "Power BI & DAX", category: "TOOL", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "Data Modeling & Data Warehousing", category: "CORE", importance: "MUST_HAVE" },
      { name: "Statistical Analysis & A/B Testing", category: "CORE", importance: "MUST_HAVE" },
      { name: "E-Commerce & Retail", category: "DOMAIN", importance: "MUST_HAVE" },
    ],
    jobDescription: `Gia nhập đội ngũ Data Growth của Shopee tại TP.HCM. Thu nhập cạnh tranh từ 50 - 75 triệu VNĐ.`,
  },
  {
    id: "job-ba-senior-dn-07",
    title: "Senior Business Analyst (Smart Supply Chain & SAP ERP)",
    company: "CJ Logistics Vietnam Dong Nai Operations",
    companyLogo: getCompanyLogoUrl("CJ Logistics"),
    location: "DONG_NAI",
    locationDetails: "KCN Long Thành, Tỉnh Đồng Nai (Xe đưa rước từ TP.HCM)",
    roleCategory: "BUSINESS_ANALYST",
    seniority: "SENIOR",
    salaryRange: {
      min: 40000000,
      max: 55000000,
      currency: "VND",
      display: "40 - 55 Triệu VNĐ (~$1.600 - $2.200)",
    },
    workMode: "HYBRID",
    experienceYearsRequired: 4,
    postedDate: "2026-08-16",
    isHot: true,
    linkedinUrl: "https://www.linkedin.com/jobs/view/senior-ba-supplychain-cj-dongnai",
    responsibilitiesSummary: [
      "Chủ trì khảo sát và tái cấu trúc luồng quy trình chuỗi cung ứng, kho tự động WMS và vận tải logistics.",
      "Soạn thảo tài liệu đặc tả yêu cầu BRD/SRS nâng cấp các phân hệ SAP ERP (MM/WM/SD).",
      "Vẽ sơ đồ quy trình nghiệp vụ BPMN 2.0 tích hợp giữa hệ thống ERP trung tâm và các Hub kho Đồng Nai.",
      "Lập kế hoạch và trực tiếp điều phối các đợt kiểm thử chấp nhận người dùng UAT toàn diện.",
    ],
    requirementsSummary: [
      "Từ 4 năm kinh nghiệm làm Senior Business Analyst trong mảng Supply Chain, Logistics hoặc Nhà máy sản xuất.",
      "Thành thạo BPMN, UML, viết User Story và quản lý yêu cầu theo chuẩn BABOK.",
      "Kỹ năng SQL tốt để đối soát dữ liệu và phân tích báo cáo tồn kho.",
      "Giao tiếp xuất sắc với ban giám đốc vận hành chuỗi cung ứng.",
    ],
    extractedSkills: [
      { name: "Requirements Engineering", category: "CORE", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "Process Modeling (BPMN/UML)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "Supply Chain & Logistics", category: "DOMAIN", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "SQL (Advanced Querying)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "UAT & Solution Evaluation", category: "CORE", importance: "MUST_HAVE" },
      { name: "Stakeholder Management", category: "SOFT_SKILL", importance: "MUST_HAVE" },
    ],
    jobDescription: `Dẫn dắt chuyển đổi số kho vận thông minh tại Đồng Nai với mức lương từ 40 - 55 triệu VNĐ.`,
  },
  {
    id: "job-da-senior-dn-10",
    title: "Senior Data & BI Specialist (Smart Factory & IoT)",
    company: "Bosch Vietnam Plant Dong Nai",
    companyLogo: getCompanyLogoUrl("Bosch"),
    location: "DONG_NAI",
    locationDetails: "KCN Long Thành, Tỉnh Đồng Nai",
    roleCategory: "DATA_ANALYST",
    seniority: "SENIOR",
    salaryRange: {
      min: 1700,
      max: 2600,
      currency: "USD",
      display: "$1.700 - $2.600 USD (~43 - 66 Tr VNĐ)",
    },
    workMode: "HYBRID",
    experienceYearsRequired: 3.5,
    postedDate: "2026-08-15",
    isHot: true,
    linkedinUrl: "https://www.linkedin.com/jobs/view/senior-da-bosch-dongnai",
    responsibilitiesSummary: [
      "Phân tích dữ liệu cảm biến IoT nhà máy, tối ưu hiệu suất dây chuyền OEE và dự báo sự cố bảo trì.",
      "Thiết kế và triển khai hệ thống báo cáo điều hành Power BI và Tableau theo dõi thời gian thực cho nhà máy.",
      "Ứng dụng Python để phân tích thống kê nâng cao và xây dựng mô hình dự báo sản lượng.",
      "Xây dựng kiến trúc dữ liệu DWH phục vụ toàn bộ các phân xưởng nhà máy Bosch tại Đồng Nai.",
    ],
    requirementsSummary: [
      "Tối thiểu 3.5 năm kinh nghiệm làm Data Analyst / BI Specialist trong môi trường công nghiệp hoặc chuỗi cung ứng.",
      "Thành thạo Power BI, viết DAX phức tạp, Power Query và thiết kế Star Schema.",
      "Thành thạo SQL nâng cao và lập trình phân tích dữ liệu với Python (Pandas, NumPy).",
      "Tiếng Anh giao tiếp tốt trong môi trường tập đoàn quốc tế.",
    ],
    extractedSkills: [
      { name: "Power BI & DAX", category: "TOOL", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "SQL (Advanced Querying)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "Python for Data Analytics", category: "CORE", importance: "MUST_HAVE", yearsRequired: 2 },
      { name: "Data Modeling & Data Warehousing", category: "CORE", importance: "MUST_HAVE" },
      { name: "Statistical Analysis & A/B Testing", category: "CORE", importance: "MUST_HAVE" },
      { name: "Supply Chain & Logistics", category: "DOMAIN", importance: "MUST_HAVE" },
    ],
    jobDescription: `Tham gia trực tiếp sáng kiến Smart Factory của Bosch tại Đồng Nai với gói thu nhập $1.700 - $2.600 USD.`,
  },
  {
    id: "job-ba-lead-hcm-09",
    title: "Lead Business Analyst (Core Banking & Enterprise Architecture)",
    company: "FPT Software Strategic Banking Unit",
    companyLogo: getCompanyLogoUrl("FPT Software"),
    location: "HO_CHI_MINH",
    locationDetails: "Khu Công nghệ cao (SHTP), TP. Thủ Đức, TP.HCM",
    roleCategory: "BUSINESS_ANALYST",
    seniority: "LEAD_MANAGER",
    salaryRange: {
      min: 48000000,
      max: 75000000,
      currency: "VND",
      display: "48 - 75 Triệu VNĐ (~$1.900 - $3.000)",
    },
    workMode: "HYBRID",
    experienceYearsRequired: 5,
    postedDate: "2026-08-16",
    isHot: true,
    linkedinUrl: "https://www.linkedin.com/jobs/view/lead-ba-fpt-hcm",
    responsibilitiesSummary: [
      "Định hình khung giải pháp và phân tích kiến trúc nghiệp vụ cho dự án chuyển đổi số ngân hàng quy mô lớn.",
      "Quản lý đội ngũ 6-10 Business Analysts, chuẩn hóa chất lượng hồ sơ BRD, SRS và kiểm thử UAT.",
      "Làm việc trực tiếp với ban điều hành C-level và các đối tác tài chính quốc tế để thống nhất phạm vi giải pháp.",
      "Tối ưu hóa quy trình phân tích theo chuẩn BABOK v3 và mô hình Agile quy mô lớn.",
    ],
    requirementsSummary: [
      "Từ 5 năm kinh nghiệm IT BA, trong đó có ít nhất 2 năm ở vai trò Lead BA hoặc Chuyên gia phân tích giải pháp.",
      "Am hiểu sâu rộng về nghiệp vụ Core Banking, Payment, Lending hoặc Open Banking API.",
      "Chứng chỉ CCBA/CBAP hoặc PSPO là lợi thế.",
      "Khả năng đàm phán, quản lý các bên liên quan và tiếng Anh thành thạo.",
    ],
    extractedSkills: [
      { name: "Requirements Engineering", category: "CORE", importance: "MUST_HAVE", yearsRequired: 5 },
      { name: "Process Modeling (BPMN/UML)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 5 },
      { name: "Stakeholder Management", category: "SOFT_SKILL", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "Fintech & Banking", category: "DOMAIN", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "SQL (Advanced Querying)", category: "CORE", importance: "MUST_HAVE" },
      { name: "User Story & Acceptance Criteria", category: "CORE", importance: "MUST_HAVE" },
    ],
    jobDescription: `Dẫn dắt các đại dự án phần mềm ngân hàng số thế hệ mới tại TP.HCM với mức lương 48 - 75 triệu VNĐ.`,
  },
  {
    id: "job-hybrid-senior-hcm-05",
    title: "Senior Product Business & Data Analyst",
    company: "MoMo (M-Service) Financial Center",
    companyLogo: getCompanyLogoUrl("MoMo"),
    location: "HO_CHI_MINH",
    locationDetails: "Quận 7, TP. Hồ Chí Minh",
    roleCategory: "HYBRID_BA_DA",
    seniority: "SENIOR",
    salaryRange: {
      min: 40000000,
      max: 60000000,
      currency: "VND",
      display: "40 - 60 Triệu VNĐ (~$1.600 - $2.400)",
    },
    workMode: "HYBRID",
    experienceYearsRequired: 4,
    postedDate: "2026-08-16",
    isHot: true,
    linkedinUrl: "https://www.linkedin.com/jobs/view/senior-hybrid-ba-da-momo-hcm",
    responsibilitiesSummary: [
      "Chủ trì phân tích tính năng sản phẩm tài chính và đào sâu dữ liệu hành vi người dùng hàng triệu giao dịch mỗi ngày.",
      "Viết tài liệu User Story, Acceptance Criteria và thiết kế dashboard phân tích phễu chuyển đổi.",
      "Chủ trì các thử nghiệm A/B Testing đo lường tác động của tính năng mới.",
      "Đồng hành cùng ban giám đốc sản phẩm từ giai đoạn định hình đến phát hành giải pháp.",
    ],
    requirementsSummary: [
      "Từ 4 năm kinh nghiệm kết hợp giữa Product BA và Data Analytics tại các công ty Fintech/Công nghệ.",
      "Nắm vững cả đặc tả yêu cầu phần mềm và xử lý dữ liệu với SQL, Power BI, Python cơ bản.",
      "Tư duy định lượng vững chắc và khả năng ra quyết định dựa trên dữ liệu.",
    ],
    extractedSkills: [
      { name: "Requirements Engineering", category: "CORE", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "SQL (Advanced Querying)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "Power BI & DAX", category: "TOOL", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "User Story & Acceptance Criteria", category: "CORE", importance: "MUST_HAVE" },
      { name: "Statistical Analysis & A/B Testing", category: "CORE", importance: "MUST_HAVE" },
      { name: "Fintech & Banking", category: "DOMAIN", importance: "MUST_HAVE" },
    ],
    jobDescription: `Vị trí Senior Hybrid BA & DA tại kỳ lân công nghệ MoMo TP.HCM. Thu nhập 40 - 60 triệu VNĐ.`,
  },
  {
    id: "job-da-lead-dn-11",
    title: "Lead Data Analytics & Digital Supply Chain",
    company: "Nestlé Vietnam Dong Nai Regional Hub",
    companyLogo: getCompanyLogoUrl("Nestlé"),
    location: "DONG_NAI",
    locationDetails: "KCN Amata, TP. Biên Hòa, Tỉnh Đồng Nai",
    roleCategory: "DATA_ANALYST",
    seniority: "LEAD_MANAGER",
    salaryRange: {
      min: 1800,
      max: 2800,
      currency: "USD",
      display: "$1.800 - $2.800 USD (~45 - 71 Tr VNĐ)",
    },
    workMode: "HYBRID",
    experienceYearsRequired: 5,
    postedDate: "2026-08-16",
    isHot: true,
    linkedinUrl: "https://www.linkedin.com/jobs/view/lead-da-nestle-dongnai",
    responsibilitiesSummary: [
      "Quản lý khung kiến trúc dữ liệu và báo cáo phân tích chuỗi cung ứng cho các nhà máy Nestlé tại Đồng Nai.",
      "Xây dựng và chuẩn hóa hệ thống KPI vận hành kho vận, tỷ lệ giao hàng đúng hạn OTIF và vòng quay tồn kho.",
      "Dẫn dắt đội ngũ phân tích dữ liệu triển khai các giải pháp trực quan hóa trên Power BI và Azure Synapse.",
      "Làm việc với các giám đốc chuỗi cung ứng vùng để đưa ra chiến lược phân bổ nguồn lực dựa trên dữ liệu.",
    ],
    requirementsSummary: [
      "Từ 5 năm kinh nghiệm về Data Analytics / Business Intelligence, trong đó có kinh nghiệm trong ngành FMCG, Sản xuất hoặc Supply Chain.",
      "Thành thạo SQL nâng cao, Power BI (DAX chuyên sâu), Data Modeling (Kimball/Star Schema).",
      "Khả năng lãnh đạo, tư duy chiến lược và tiếng Anh lưu loát.",
    ],
    extractedSkills: [
      { name: "Power BI & DAX", category: "TOOL", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "SQL (Advanced Querying)", category: "CORE", importance: "MUST_HAVE", yearsRequired: 4 },
      { name: "Supply Chain & Logistics", category: "DOMAIN", importance: "MUST_HAVE", yearsRequired: 3 },
      { name: "Data Modeling & Data Warehousing", category: "CORE", importance: "MUST_HAVE" },
      { name: "Statistical Analysis & A/B Testing", category: "CORE", importance: "MUST_HAVE" },
    ],
    jobDescription: `Cơ hội dẫn dắt mảng phân tích dữ liệu chuỗi cung ứng tại tập đoàn Nestlé Đồng Nai với gói thu nhập $1.800 - $2.800 USD.`,
  },
];
